### ISSUE TITLE
Cannot use it on a CPU-only PC right?

### ISSUE THREAD

**Issue by kyonkoo** [alreadydone/lz#106]
I only have a XPS13 as my PC which as you know doesn't have a stand-alone GPU.
Of course I have read this thread: https://github.com/alreadydone/lz/issues/59 and followed your instruction, but still failed to attach it in Sabaki. (cannot complete 290 valid configurations)
My Sabaki works well with CPU-only leela zero though.

My setting:
--tg-auto-pn --neg --gtp --noponder -w D:\G\Sabaki\leela-zero-0.17-cpuonly-win64\OZ31.txt.gz --target-komi 0

The log:
Using 2 thread(s).
RNG seed: 5651550718598132877
BLAS Core: Haswell
Detecting residual layers...v1...256 channels...30 blocks.
Initializing OpenCL (autodetect precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.1 
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 620
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 23.20.16.4973
Device speed:  1000 MHz
Device cores:  24 CU
Device score:  621
Device ID:     1
Device name:   Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 7.6.0.611
Device speed:  2500 MHz
Device cores:  4 CU
Device score:  521
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 620
with OpenCL 2.1 capability.
Half precision compute support: YES
Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 2.2064 ms (53.5 GFLOPS)
(4/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.9014 ms (62.0 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.6782 ms (70.3 GFLOPS)

**Comment by alreadydone** [comment]
Does it work if you add --cpu-only to your command?

**Comment by kyonkoo** [comment]
> Does it work if you add --cpu-only to our command?

Oh my mistake, it really works with --cpu-only! Thanks!

And it also works in lizzie after adding --cpu-only! Such a great work!
