### ISSUE TITLE
Could you please make a phoenix-orig-mt of cpu version?

### ISSUE THREAD

**Issue by 1-punchMan** [alreadydone/lz#39]
In [PhoenixGo + dynamic komi](https://github.com/alreadydone/lz/releases), readme says you modified parameters in @yenw's [LeelaZero_PhoenixGo](https://github.com/yenw/LeelaZero_PhoenixGo/) to match the [original PhoenixGo engine](https://github.com/Tencent/PhoenixGo/releases/tag/win-x64-gpu-v1). And it's a gpu version. Could you please make a phoenix-orig-mt of cpu version? Thanks a lot!

**Comment by alreadydone** [comment]
I updated https://github.com/alreadydone/lz/releases/tag/phoenix-v0.33 with a CPU version (phoenix-orig only). It may not be a good idea to run such a big net on CPU, though.

**Comment by 1-punchMan** [comment]
Thank you! 
Since I only use the original GPU in my computer, I found Leela zero's network pondered faster using CPU than GPU. And [LeelaZero_Phoenix's network](https://github.com/yenw/LeelaZero_PhoenixGo/releases/tag/v1) pondered much more slowly on both CPU and GPU.
