### ISSUE TITLE
Dynamic komi versions

### ISSUE THREAD

**Issue by Marcin1960** [alreadydone/lz#43]
I got completely confused.

1. What is the real difference between?

"Dynamic komi for handicap games" /  komi-v0.3

and

"Adjustable target komi" /  komi-v0.31

2. Are the sets of after release commits the same for each?

**Comment by alreadydone** [comment]
v0.31 is just one commit away from v0.3, which introduced one variable target_komi. If you set target_komi to 7.5f, its behavior will be identical to v0.3. That's why there's a target=-7.5 version and a target=0.0 version but not a target=7.5 version.
v0.3 and v0.31 are different points on the komi branch, which is now abandoned. I am working on the komi+ branch which combines the old komi branch and the endgame branch.

**Comment by Marcin1960** [comment]
I cannot help much from technical side. But at least I will be running a  KGS bot (LeelaZeroT) with your binary,  pointing to your work. Maybe it will attract some contributors to help you.

I am concerned that the pursuit of mere tournament strength and size in the main branch of LZ will lead nowhere. The real perspectives are in other objectives like your work, in horizontal, not only vertical growth. 

Best luck, and thank you.

**Comment by Marcin1960** [comment]
I disabled limit on pondering, so all time will be used, by this hack. I hope it will work:

I changed one line in UCTSearch (line 801) to:
keeprunning &= true; //keeprunning &= !stop_thinking(0, 1);

See:

https://github.com/gcp/leela-zero/issues/1702

KGS bot is running as LeelaZeroT (get handicap from 2 to 5 or bot will quit)

**Comment by alreadydone** [comment]
I believe your change has identical effect as commenting out the whole line.
Doesn't the time setting approach evdwerf eventually takes work for you?

**Comment by Marcin1960** [comment]
Is the komi+next branch the main one?

Does it make sens to compile it and run it on KGS? Or it is not ready yet?

**Comment by alreadydone** [comment]
Yes you may compile it and run it on KGS with the --handicap option.
It's stronger than komi-v0.3, but it still crashes often according to testers, and I'm not sure about the reason.

**Comment by Marcin1960** [comment]
OK, I will try

**Comment by alreadydone** [comment]
The code now automatically detects suitability of the network (weights file) and automatically set --pos or --neg if deemed necessary. If a network is deemed not suitable, the engine will simply quit, but you can force using the network with the option --tg-auto-pn (with which you can also manually set --pos or --neg).
The crashes on my machine seem to almost exclusively happen with more than one thread, mostly with --pos or --neg enabled, and mostly happen post-endgame (when both sides are filling in their own territories).

**Comment by Marcin1960** [comment]
1.
--benchmark does not work on my PC (Win32) . Nothing happens on the screen while CPU is busy). Had to use ctrl C to break.

2
For KGS play, what options do you recommend beside "--handicap", "--min-wr 0.32 --max-wr 0.45" ?

**Comment by alreadydone** [comment]
1. --benchmark works with my latest build on my machine. You may also want to check whether it works on your machine with latest gcp/next; there has been many network related changes.

2. That should be good enough, but maybe also --target-komi 0? Also due to more stable/accurate komi adjustment lower --min-wr and --max-wr possibly work better now.

The latest komi+next branch should be free of crashes.

**Comment by Marcin1960** [comment]
OK, I compiled the latest release 0.4.

=======

Benchmark still does not work or rather takes a very long time (extra 20 minutes, with heavy CPU use) before output. My build is 32 bit Windows, SDK is of earlier version - 10.0.16299.0.

C:\Program Files\LeelaZero_0.15>lz-komi-v0.4 -t 1 --tune-only -w e1d46_15x192
Using 1 thread(s).
RNG seed: 13118019218003215661
Leela Zero 0.15  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL (autodetect precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.0 AMD-APP (1800.8)
Platform profile: FULL_PROFILE
Platform name:    AMD Accelerated Parallel Processing
Platform vendor:  Advanced Micro Devices, Inc.
Device ID:     0
Device name:   Capeverde
Device type:   GPU
Device vendor: Advanced Micro Devices, Inc.
Device driver: 1800.8 (VM)
Device speed:  880 MHz
Device cores:  8 CU
Device score:  1120
Device ID:     1
Device name:   Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
Device type:   CPU
Device vendor: GenuineIntel
Device driver: 1800.8 (sse2)
Device speed:  2992 MHz
Device cores:  4 CU
Device score:  520
Selected platform: AMD Accelerated Parallel Processing
Selected device: Capeverde
with OpenCL 2.0 capability.
Half precision compute support: NO

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
Failed to compile: 290 kernels.
Failed to find a working configuration.
Check your OpenCL drivers.
Minimum error: 100.000000. Error bound: 0.100000
Failed to initialize half precision net.  Resorting to single precision.
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.0 AMD-APP (1800.8)
Platform profile: FULL_PROFILE
Platform name:    AMD Accelerated Parallel Processing
Platform vendor:  Advanced Micro Devices, Inc.
Device ID:     0
Device name:   Capeverde
Device type:   GPU
Device vendor: Advanced Micro Devices, Inc.
Device driver: 1800.8 (VM)
Device speed:  880 MHz
Device cores:  8 CU
Device score:  1120
Device ID:     1
Device name:   Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
Device type:   CPU
Device vendor: GenuineIntel
Device driver: 1800.8 (sse2)
Device speed:  2992 MHz
Device cores:  4 CU
Device score:  520
Selected platform: AMD Accelerated Parallel Processing
Selected device: Capeverde
with OpenCL 2.0 capability.
Half precision compute support: NO

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2637 ms (251.6 GFLOPS)
(2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2144 ms (309.5 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.1849 ms (359.0 GFLOPS)
(223/290) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=4 0.1834 ms (361.9 GFLOPS)

C:\Program Files\LeelaZero_0.13>lz-komi-v0.4 -t 1 --benchmark -w e1d46_15x192
Failed to compile: 290 kernels.
Failed to find a working configuration.
Check your OpenCL drivers.
Minimum error: 100.000000. Error bound: 0.100000
Thinking at most 2678400.0 seconds...
black positions: 0
white positions: 0
NN eval=0.539211
Playouts: 222, Win: 54.33%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3
Playouts: 464, Win: 54.29%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4
Playouts: 703, Win: 54.26%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2
Playouts: 945, Win: 54.25%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5
Playouts: 1192, Win: 54.25%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3
Playouts: 1439, Win: 54.23%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1
Playouts: 1689, Win: 54.24%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4
Playouts: 1936, Win: 54.23%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4 R2
Playouts: 2184, Win: 54.24%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4 R2
Playouts: 2434, Win: 54.24%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4 R2 S7 Q6
Playouts: 2684, Win: 54.25%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4 R2 S7 Q6 R7
Playouts: 2936, Win: 54.25%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4 R2 S7 Q6 R7
Playouts: 3195, Win: 54.25%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4 R2 S7 Q6 R7

  D3 ->    1705 (V: 54.33%) (N: 47.39%) PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4 R2 S7 Q6 R7
  C4 ->    1198 (V: 54.24%) (N: 35.81%) PV: C4 D3 F3 E3 E4 F2 Q4 D16 P17 Q17 P16 R14 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 H17 R3 Q3
 D16 ->      96 (V: 53.85%) (N:  3.70%) PV: D16 C4 D5 D3 Q4 O17 F4 C6 R6 C14 F17
  Q4 ->      93 (V: 53.87%) (N:  3.56%) PV: Q4 D3 E4 C4 D16 O17 D6 F3 F17 O3 R6
 D17 ->      37 (V: 53.78%) (N:  1.50%) PV: D17 C4 D5 D3 Q4 C15 P17 Q14 F4
  R4 ->      29 (V: 53.87%) (N:  1.09%) PV: R4 D3 D16 E4 P17 Q14
  Q3 ->      27 (V: 53.99%) (N:  0.96%) PV: Q3 D3 E4 C4 D16 R5 D6 F3
 C16 ->      14 (V: 53.73%) (N:  0.59%) PV: C16 C4 D5 D3 Q4
16.2 average depth, 37 max depth
2463 non leaf nodes, 1.30 average children
3200 visits, 1099895 nodes, 3199 playouts, 97 n/s


C:\Program Files\LeelaZero_0.15>

**Comment by Marcin1960** [comment]
My main suspicion is that the bugs show in 32 bit version.

Did anyone had success with 32 bit?

What about komi plus version (https://github.com/alreadydone/lz/tree/komi+). Does it have the same functionality?

**Comment by alreadydone** [comment]
komi+ branch is obsolete and doesn't have crucial fixes of crashes.
Have you tested with official gcp/next branch? I suspect you will get the some problem. There are known problems when AMD cards and half precision support work together. If that's a case you should add to the existing issues there (e.g. https://github.com/gcp/leela-zero/issues/1701, https://github.com/gcp/leela-zero/issues/1709, https://github.com/gcp/leela-zero/issues/1689).
Before that's fixed you can add `--precision single` to the command line.

**Comment by Marcin1960** [comment]
@alreadydone  "komi+ branch is obsolete and doesn't have crucial fixes of crashes"

But does it have the same functionality, I mean in terms of command line options?

Is there are an easy way to find these fixes of crashes in the code? Perhaps I can import them.
What about performance?

The reason is that I would like to  try your new stuff on KGS ;)
I will try "--precision single" too.

**Comment by alreadydone** [comment]
komi+ is out of date and doesn't have the same command line options/parameters; I won't update it since /next will eventually become the next release.
`--precision single` should work. The crash fixes are intermingled with other changes and you probably wouldn't like to apply such a big diff, though you can look at the commit history at https://github.com/gcp/leela-zero/pull/1772 after `merge /next of 0.15`.

**Comment by Marcin1960** [comment]
@alreadydone "--precision single should work"

It does work! Thanx a lot.

And v0.4 is almost 40% faster than komi plus.

**Comment by alreadydone** [comment]
v0.4 is based on the newest /next branch at gcp/leela-zero; it supports fp16 (half precision) storage and computation which are faster than fp32 (single precision) we use before. Since you are using --precision single, you probably don't benefit from fp16 computation, but may still benefit from fp16 storage.
