### ISSUE TITLE
Endgame Leela always stops early, costing up to half the visits.

### ISSUE THREAD

**Issue by anonymousAwesome** [alreadydone/lz#44]
Even when komi adjustment hasn't been activated yet, Endgame Leela will always stop early.  With pondering off, visits limited to 600, and thinking time an arbitrarily high number, Endgame Leela will make anywhere from 600 to 300 visits on any given turn.  In the same situations Leela (the original program) takes all 600 visits per turn.

**Comment by anonymousAwesome** [comment]
Never mind, it was confirmation bias.  Vanilla Leela seems to exhibit this behavior as well.

**Comment by anonymousAwesome** [comment]
For some reason it only shows up in one specific situation I've found so far, when GX37 endgame plays against GX37 non-endgame.  Non-endgame GX37 uses all 600 visits, but LZ 157 doesn't and GX37 endgame doesn't.  Weird.  Whatever the reason, turning off time management fixes it.

**Comment by alreadydone** [comment]
Time management takes effect when one move gets much more visits than the others. Maybe when winrate is too high or low, the policy becomes flat and no one move is singled out.
