### ISSUE TITLE
Half precision not supported on vega56

### ISSUE THREAD

**Issue by ghost** [alreadydone/lz#51]
On my Windows 7 running vega 56, half precision doesn't work. Single precision works fine.

leelaz.exe -w lz157.gz --benchmark --precision half

Thinking at most 2678400.0 seconds. . .
black position: 0
white position: 0
NN eval=-nan(ind)

**Comment by alreadydone** [comment]
You should file an issue with gcp/leela-zero; half precision wasn't implemented by me.
There are existing discussions about AMD cards there.
When half precision doesn't work you can just force --precision single.
