### ISSUE TITLE
Can't find the readme on your recent release

### ISSUE THREAD

**Issue by anonymousAwesome** [alreadydone/lz#52]
I see it in the pull request for Leela Zero, but I can't find it anywhere in the actual files.  The included readme.md is identical to the one for Leela Zero and says nothing about dynamic komi.

**Comment by alreadydone** [comment]
It's in the release https://github.com/alreadydone/lz/releases/tag/komi%2Bv0.41 and named README.md.txt.

**Comment by anonymousAwesome** [comment]
No it isn't.  I downloaded the .tar.gz file and the .zip file and it's not there.

**Comment by anonymousAwesome** [comment]
...oh, I see.  You included it with the release but you didn't put them in the actual git repo.  Would it be possible for you to move the readme file to the git repo?  When I (or anybody else) downloads the source files directly from Github the readme won't be in there.

**Comment by alreadydone** [comment]
Done.
