### ISSUE TITLE
Placing 5 or more handicap stones... Error on Nvidia K80

### ISSUE THREAD

**Issue by zhanzhenzhen** [alreadydone/lz#55]
I'm testing the 15b model (d351):

```
./leelaz -w leelaz-model-15b.gz --handicap -r 0 --target-komi 0
play b r16
play b p16
play b k10
play b c4
play b r4
genmove w
```

It says:

```
Thinking at most 37.9 seconds...
black positions: 0
white positions: 0
deleting non-descendents
black positions: 0
white positions: 0
keeping 4.000000% closest evals
black positions: 8
white positions: 8
Segmentation fault (core dumped)
```

Testing environment:

AWS EC2 p2.xlarge, Deep Learning AMI (Ubuntu) Version 13.0
All needed libraries are preinstalled. So just type "make".

**Comment by zhanzhenzhen** [comment]
I'm using v0.42 (commit `f0bab87b2624a50c89ac02d1af1648a92404c67e`)

**Comment by alreadydone** [comment]
> black positions: 0
> white positions: 0
> deleting non-descendents
> black positions: 0
> white positions: 0

These aren't normal; the numbers should be 200 or a bit more. If they are 0 the `keeping 4.000000% closest evals` shouldn't appear. The problem has been observed by another guy using Linux (both in (my)lizzie and in Sabaki), but never observed under Windows, and I don't have Linux environment to test right now... I don't know how the same C++ code could behave differently under Windows and Linux.

**Comment by zhanzhenzhen** [comment]
@alreadydone OK. BTW, not only Linux, but macOS also has a similar problem, plus it takes a very long time to initiate.

**Comment by alreadydone** [comment]
/next branch has automatic detection of fp16 support (and comparison with the speed of fp32) at startup which takes some time. My branch has a test for dynamic komi at startup that needs to run the network 600 times (a bit more time than 600 playouts) **(can be disabled with --tg-auto-pn)**.

**Comment by Ka-zam** [comment]
See the discussion on discord also but mean_white_eval(..) tries to access 
    ssi[0]->state.m_stm_komi
and since ssi[0]->state is an instance of GameState not FastState this is an illegal access.

**Comment by Ka-zam** [comment]
> The problem has been observed by another guy using Linux (both in (my)lizzie and in Sabaki), but never  observed under Windows, and I don't have Linux environment to test right now... I don't know how the same C++ code could behave differently under Windows and Linux.

One conceivable way this can happen is if you have code that reaches an undefined state. Trying to access member variables that don't exist is undefined behavior. On Windows perhaps your threads take longer to initialize and therefore you never reach the offending code.

**Comment by alreadydone** [comment]
Try latest komi+next; seems to be a problem with initializating boolean to true. Sorry for taking so long to realize.

**Comment by Ka-zam** [comment]
Works fine now.

**Comment by zhanzhenzhen** [comment]
Thank you. Just tested and this patch works fine on Ubuntu now.

But macOS still has some problems. Let me create another issue.

**Comment by seopsx** [comment]
I'm getting this error on Ubuntu 18.04, v0.42 and with any number of handicap.


```
./leelaz --handicap -t 4 -r 0 --gtp -w LeelaMaster_GX37.txt
Negative komi total score: 2.281690e-02
Positive komi total score: 2.200511e-02
Weight file is of good quality for dynamic komi! Ȩ���������������������ӣ������ð档
fixed_handicap 2
= D4 Q16

genmove w
Thinking at most 36.0 seconds...
black positions: 0
white positions: 0
deleting non-descendents
black positions: 0
white positions: 0
keeping 4.000000% closest evals
black positions: 8
white positions: 8
Segmentation fault (core dumped)

```

**Comment by alreadydone** [comment]
This problem has been fixed. You need the latest komi+next branch.

**Comment by seopsx** [comment]
Thank you.
