### ISSUE TITLE
布了个阵，参数怎么设置啊？

### ISSUE THREAD

**Issue by zhanzhenzhen** [alreadydone/lz#58]
白棋还是会在右面和下面乱走，怎样让它下在左上角呢？

![handicap](https://user-images.githubusercontent.com/731796/45184661-2efe0400-b25a-11e8-83c8-1c70ed21288f.png)

**Comment by alreadydone** [comment]
可以尝试提高--min-wr和--max-wr(默认0.06, 0.12)，如果不行也没办法，网络对这样的局面太不熟悉了

**Comment by Marcin1960** [comment]
Google translator:

White will still go on the right and below, how to make it in the upper left corner?

==========

You can try to increase --min-wr and --max-wr (default 0.06, 0.12). If you can't do it, the network is too unfamiliar with this situation.
