### ISSUE TITLE
"Initializing CPU-only evaluation" every time I switch weights.

### ISSUE THREAD

**Issue by anonymousAwesome** [alreadydone/lz#59]
When I try to use your newest commit of komi+next, the engine spends several minutes "initializing CPU-only evaluation".  The first time it does this is useful; it helps me figure out which weights would be best.  The problem is, it does this every single time I use a new weight, even if it's one it evaluated before.  This is frustrating; I switch between several different weights over the course of reviewing a game, and I absolutely do not want to wait the several minutes it takes for the evaluation to complete every single time.

EDIT: I tried commenting it out and the program segfaulted, so I assume it's doing something more important than just "let the user know if the weights will work".  At the very least, can we get it to store the results of the analyses somewhere on the hard drive so that I don't have to go through this every time I switch weights?

**Comment by alreadydone** [comment]
So you don't have a GPU? You may add the option --tg-auto-pn to disable the dynamic komi suitability test (and set --pos or --neg according to the instruction you get the first time you run with the weight).
