### ISSUE TITLE
"Weight file is unusable"

### ISSUE THREAD

**Issue by evalon32** [alreadydone/lz#64]
I'm trying to run the latest komi+next with recent networks from zero.sjeng.org, and unless I pass `--tg-auto-pn`, I always get 

> Weight file is unusable for dynamic komi. Sorry.

Full output: https://gist.github.com/evalon32/2860349e1360aff44ce7fdf1aa8981cf.

Which files _are_ usable, then?

**Comment by alreadydone** [comment]
I recommend pangafu's Leela Master weights at https://drive.google.com/drive/folders/1XrdAxjDQ7Dnz49QRdv9Dfm1P__-rwR3L
It's [reported](https://github.com/pangafu/LeelaMasterWeight/blob/master/README.md#about-handicap-game%E5%85%B3%E4%BA%8E%E8%AE%A9%E5%AD%90%E6%A3%8B) that GX37 and GX38 work well, but you may also try more recent network files, which are trained with more recent LZ self-play data but have more human games mixed in.

**Comment by evalon32** [comment]
Ah, I see. GX38 worked. The latest (GX68) did not.
