### ISSUE TITLE
关于贴目6.5及不退让模式

### ISSUE THREAD

**Issue by zsalch** [alreadydone/lz#69]
非常感谢您对动态贴目及不退让模式的贡献。

我尝试了贴6.5目模式，选了0.5目胜负的一盘棋，命令配置如下：
./lzkomi --gtp --lagbuffer 0 --weights leelaz_153_e1d --threads 2 --target-komi 3
结果如下图：
![image](https://user-images.githubusercontent.com/42595514/48005023-56cff200-e14d-11e8-86af-34f5c0046ade.png)

对应标准Leela Zero结果:
![image](https://user-images.githubusercontent.com/42595514/48005187-bcbc7980-e14d-11e8-8720-3b818cd4dc59.png)

已经可以识别出正确的结果，非常棒。不知道参数如何进一步优化，如有时间，请不吝指导，谢谢。

另外尝试了不退让模式，参数如下：
./lzkomi --gtp --lagbuffer 0 --weights leelaz_153_e1d --threads 2 --nonslack --max-wr 0.9 --min-wr 0.1 --wr-margin 0.05

启动时需要经过漫长地初始化，不知道是参数设置有误，还是必须的初始过程：
komi | winrate
---- | ----
-300.000000 | 1.000000
-299.500000 | 1.000000
-299.000000 | 1.000000
-298.500000 | 1.000000
...
299.500000 | 0.127762
300.000000 | 0.128868
????????Ŀֵ????ʤ?????????ģ?Winrate increasing near 130.5, 132.0, 132.5, 133.0, 133.5, 134.0, 134.5, 
...
298.0, 298.5, 299.0, 299.5, 300.0, .
Negative komi total score: 0.000000e+00
Positive komi total score: 2.672276e-01
Weight file is of mediocre quality for dynamic komi. Use with the option --neg. Ȩ???????еȣ?????Ŀ???ֲ??ѣ??Ƽ?ʹ??--neg??????
Automatically set --neg.

**Comment by alreadydone** [comment]
您好，同样感谢您对Lizzie的贡献！
动态贴目最主要的应用是下让子棋，贴6.5模式属于静态贴目，并没有什么参数可以调整，最高最低胜率等只在让子或不退让贴目模式下才可以设置。
漫长的初始化是为了检测权重是否适用于动态贴目，可以加--tg-auto-pn选项跳过，但是基于以上检测的结果，建议对153号权重同时加上--neg选项。对于第一次使用的权重，还是应该检测一遍。
合适的让子参数参见https://github.com/alreadydone/lz/issues/54#issuecomment-423034291 ，因为我自己无力测试，参数是参考大师茶楼QQ群里的意见，GX37和65据称是较好的让子权重。群里高手云集，研究氛围浓厚，还有章鱼围棋的作者和LeelaMaster训练者pangafu坐镇，并不断推出修改版引擎。不退让也能用来下6.5贴目的棋，但参数权重未见有太多的研究。(如有兴趣请告知QQ号以便邀请入群)

**Comment by zsalch** [comment]
那非常荣幸，我稍后邮件发送QQ号，谢谢。

**Comment by hankchang0611** [comment]
第一次用github，找不到私訊樓主的地方，只好發在這了，希望樓主能看到。
我不管用哪個權重都會顯示：
Weight file is unusable for dynamic komi. Sorry. 
不知道是哪裡的設置有問題？
用過gx37、gx65、oz38，都會出現這段訊息。

**Comment by alreadydone** [comment]
可能是显卡或驱动程式的问题。在leelaz命令后加上--tg-auto-pn可以强制使用权重。
